name: Deploy alexgogogo to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DEPLOY_TOKEN }}
          script: |
            cd aleeeeexgogogo
            git pull origin main
            docker build -t alexgogogo .
            docker stop next-app || true
            docker rm next-app || true
            docker run -d -p 3000:3000 --name next-app alexgogogo
