name: Deploy alexgogogo to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1  # 使用新版 Action
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DEPLOY_TOKEN }}
          script: |
            cd aleeeeexgogogo || exit 1
            git pull origin main || exit 1
            # 强制清理旧容器
            docker rm -f alexgogogo 2>/dev/null || true
            # 构建并启动新容器
            docker build --no-cache -t alexgogogo . 
            docker run -d --restart unless-stopped -p 3000:3000 --name next-app alexgogogo