name: Deploy alexgogogo to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DEPLOY_TOKEN }}
          script: |
            cd aleeeeexgogogo || exit 1
            git pull origin main || exit 1
            docker ps -q --filter "name=alexgogogo" | grep -q . && docker stop alexgogogo
            docker ps -aq --filter "name=alexgogogo" | grep -q . && docker rm alexgogogo
            docker build --no-cache -t alexgogogo . || exit 1
            docker run -d --restart unless-stopped -p 3000:3000 --name next-app alexgogogo || exit 1
